### ISSUE TITLE
HTTP 404 Error When Trying to View Split Item

### ISSUE THREAD

**Issue by donwitcher** [snuziale/vsts-extension-split-work#15]
After splitting an item, you'll see a message similar to "This work item was split from work item 12345." When you click the link for "12345" you get an HTTP 404 message.

**Comment by prawnz** [comment]
I noticed this as well. I believe it is an issue with the url as the comments showing as this
https://xxx.visualstudio.com/tfs/_permalink/_workitems/edit/NNNN

while viewing the parent items url it is showing
https://XXX.visualstudio.com/<ProjectName>/_workitems/edit/NNNN

Can this be fix?

**Comment by clpatp** [comment]
We have the same problem. It is quite annoying since you have to go to greater lenghts to follow the tasks and user stories.

**Comment by RicardoLans** [comment]
@snuziale any chance you have time to get this working?
Looks like the extension currently works only for on-prem installations.

Lots of people are using VSTS, Azure DevOps and currently named Azure Repos.

**Comment by beccamc** [comment]
I have (mainly) fixed the link issue. Links created from now on will work. There is one caveat - the generated link only works when your using the url format **https://dev.azure.com/**<collection-org>/<project>. If you're using the old https://<collection-org>.visualstudio.com the links won't work. This is because it will put the collection/org in twice. 

The complication here is around on prem collections. We need to support on-prem urls as well as hosted urls which means I can't hard code the ".com" section. As long as you use the dev.azure.com url, the links will work perfectly.

**Comment by beccamc** [comment]
Nevermind, I found I can use collection.uri to get the correct stem for the url no matter if you're using old/new url format. This is fixed.

**Comment by beccamc** [comment]
Important to note, **this will only fix links created in new version 1.3 and newer**. Old links will still be broken.
